export const Endpoint = {
  SEND_OTP: "api/email/otp/send",
  LOGIN: "api/auth/login",
  REFRESH_TOKEN: "api/auth/refresh",
  MY_PROFILE: "api/user/myProfile",
  RECOVERY_PASSWORD: "auth/recovery",
  VERIFY_OTP: "api/email/otp/verify",
  RESET_PASSWORD: "api/auth/reset-password",
  MYINFO: "api/user/myInfo",
  UPCOMING_DUE_TASKS: "api/tasks/upcoming-due",
  MY_PROJECTS: "api/projects/my-projects",
  UPDATE_USER: "api/user/updateProfile",
  MY_PROJECTS_DROPDOWN: "api/projects/my-projects/dropdown",
  PROJECT_TASKS: "api/tasks/projects",
  UPDATE_TASK_STATUS: "api/tasks",
  TEAM_MEMBERS: "api/team-members",
  TASK_HISTORY: "api/task-history/recent",
  PROJECTS: "api/projects",
  PM_PROJECTS_DROPDOWN: "api/projects/dropdown",
  PROJECT_MEMBER_LIST: "api/team-members/projects",
  SELECT_MEMBERS: "api/users/projects",
  SPECIALIZATIONS: "api/specializations",
  ADD_TEAM_MEMBERS: "api/team-members/projects"
}; 